# LinkedOut on Fargate: the API, the portal, and the two datastores they need.
#
# ─────────────────────────────────────────────────────────────────────────────
# WHY THIS IS NOT KUBERNETES, AND WHAT THAT COSTS.
#
# LinkedOut's account fleet genuinely requires a cluster: AccountsService
# provisions a StatefulSet per LinkedIn account, proxies co-browse through the
# Kubernetes API server's portforward subresource, and execs into the worker
# container to mint a session inside the browser that will use it. None of that
# has an ECS equivalent, and the portforward tunnel has no equivalent anywhere.
#
# It is deployed here anyway because the fleet cannot run yet for an unrelated
# reason: an account binds its outbound address on first pod start, and
# NODE_ENV=production refuses to launch a browser without a proxy. No
# residential proxies have been bought. So what is deployable today is the
# control plane -- API, portal, database, queue -- and that is ordinary
# containers.
#
# The API is built to boot without a cluster. K8sApiFactory loads its kubeconfig
# lazily and on purpose ("would make the API refuse to boot anywhere without a
# kubeconfig"), PodStatusService degrades to a named error rather than throwing,
# and nothing polls Kubernetes on a timer. Onboarding an account, opening a
# co-browse session and the fleet page are the three things that will fail here,
# each with a clear message.
#
# When proxies arrive, a cluster joins this and the API moves into it. That is a
# manifest, not a rewrite.
# ─────────────────────────────────────────────────────────────────────────────

# ---- datastores -------------------------------------------------------------

resource "aws_security_group" "linkedout_data" {
  name        = "linkedout-data"
  description = "Postgres and Redis for LinkedOut; reachable from its tasks only"
  vpc_id      = data.aws_vpc.default.id
  tags        = { ManagedBy = "terraform", App = "linkedout" }
}

# Ingress as separate rules rather than inline blocks, because the source is a
# security group created by a module in this same apply -- an inline block would
# make the group depend on the service and the service on the group.
resource "aws_vpc_security_group_ingress_rule" "linkedout_postgres" {
  security_group_id            = aws_security_group.linkedout_data.id
  description                  = "Postgres from the LinkedOut API"
  from_port                    = 5432
  to_port                      = 5432
  ip_protocol                  = "tcp"
  referenced_security_group_id = module.linkedout.task_security_group_id
}

resource "aws_vpc_security_group_ingress_rule" "linkedout_redis" {
  security_group_id            = aws_security_group.linkedout_data.id
  description                  = "Redis from the LinkedOut API"
  from_port                    = 6379
  to_port                      = 6379
  ip_protocol                  = "tcp"
  referenced_security_group_id = module.linkedout.task_security_group_id
}

# The portal talks to the API over HTTP and to WorkOS. It has no database
# handle of its own and deliberately gets no rule here.

resource "aws_db_subnet_group" "linkedout" {
  name       = "linkedout"
  subnet_ids = slice(sort(data.aws_subnets.default.ids), 0, 2)
  tags       = { ManagedBy = "terraform", App = "linkedout" }
}

# db.t4g.micro, single AZ, about fifteen dollars a month.
#
# Managed rather than in-cluster or in-container, and this is the one place the
# cheap option is wrong. The database holds the suppression list, which carries
# legal weight and CANNOT BE REBUILT: entries are HMACs of SUPPRESSION_DIGEST_KEY
# and the table stores digests rather than identifiers, so there is nothing left
# to re-derive a lost row from. Queues and leases rebuild themselves; a
# do-not-contact list does not.
resource "aws_db_instance" "linkedout" {
  identifier     = "linkedout"
  engine         = "postgres"
  engine_version = "16"
  instance_class = "db.t4g.micro"

  allocated_storage     = 20
  max_allocated_storage = 100
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = "linkedout"
  username = "linkedout_root"
  # Generated by RDS and held in Secrets Manager. Never in this file, never in
  # state as a plaintext input, and never typed into a console.
  manage_master_user_password = true

  db_subnet_group_name   = aws_db_subnet_group.linkedout.name
  vpc_security_group_ids = [aws_security_group.linkedout_data.id]
  publicly_accessible    = false

  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "Mon:04:00-Mon:05:00"

  # A deletion that takes a final snapshot first. The protection is the point:
  # the suppression list is above.
  deletion_protection       = true
  skip_final_snapshot       = false
  final_snapshot_identifier = "linkedout-final"

  # Minor versions apply themselves in the maintenance window; major ones never
  # do, because a major Postgres upgrade is a decision.
  auto_minor_version_upgrade = true

  # engine_version is "16", and RDS resolves that to a minor version it then
  # raises in the maintenance window. Without this every later plan proposes
  # putting it back, and a plan that always has one line of noise in it is a
  # plan people learn to skim.
  lifecycle {
    ignore_changes = [engine_version]
  }

  tags = { ManagedBy = "terraform", App = "linkedout" }
}

# cache.t4g.micro, about twelve dollars a month.
#
# A NODE RATHER THAN SERVERLESS, AND THE FIRST DRAFT HAD THIS WRONG.
#
# It said Serverless "because the fleet is zero accounts until proxies arrive and
# a cache.t4g.micro costs twelve dollars a month to hold nothing". That reasoning
# only works if Serverless bills near zero when idle, and it does not: it bills
# stored data with a one gigabyte floor, which is roughly ninety dollars a month
# before a single command is issued. It was the largest line in the whole stack,
# to hold a few leases and counters.
#
# Serverless is the right answer for a cache whose size swings by orders of
# magnitude. This one holds per-account action queues, a single-pod lease and a
# daily cap counter -- tens of kilobytes at the scale this will run at for a
# year. A node is both cheaper and easier to reason about.
resource "aws_elasticache_replication_group" "linkedout" {
  replication_group_id = "linkedout"
  description          = "LinkedOut queues, leases and cap counters"

  engine         = "redis"
  engine_version = "7.1"
  node_type      = "cache.t4g.micro"

  # One node. Redis here is not a cache in front of a database -- it carries the
  # BullMQ queues, so losing it loses queued actions rather than degrading
  # performance. That argues for a replica eventually; it does not argue for one
  # now, while the fleet is zero accounts and a replica doubles the bill.
  num_cache_clusters = 1

  port                 = 6379
  subnet_group_name    = aws_elasticache_subnet_group.linkedout.name
  security_group_ids   = [aws_security_group.linkedout_data.id]
  parameter_group_name = "default.redis7"

  # In transit only. At-rest encryption on a single-node group holding queue
  # entries buys little and rules out the cheapest node families later.
  transit_encryption_enabled = false

  # Snapshots of a queue are of limited use -- a restored queue is a set of
  # actions somebody already decided not to take an hour ago. Kept at one day so
  # there is something to look at after an incident, not as a recovery plan.
  snapshot_retention_limit = 1
  snapshot_window          = "05:00-06:00"
  maintenance_window       = "mon:06:00-mon:07:00"

  apply_immediately = false

  tags = { ManagedBy = "terraform", App = "linkedout" }
}

resource "aws_elasticache_subnet_group" "linkedout" {
  name       = "linkedout"
  subnet_ids = slice(sort(data.aws_subnets.default.ids), 0, 2)
  tags       = { ManagedBy = "terraform", App = "linkedout" }
}

# ---- the API ----------------------------------------------------------------

module "linkedout" {
  source = "../../modules/fargate-service"

  app          = "linkedout"
  cluster_name = var.ecs_cluster_name
  vpc_id       = data.aws_vpc.default.id
  subnet_ids   = slice(sort(data.aws_subnets.default.ids), 0, 2)

  container_port = 3001
  # /health/ready, not /health. Readiness checks Postgres and Redis, so a task
  # that is running but cannot reach either stops receiving traffic rather than
  # accepting it and failing. Neither path is reachable from the internet -- see
  # the listener rule at the foot of this file.
  health_path = "/health/ready"

  # 0.5 vCPU / 1 GB rather than the smallest size. This process is not a web
  # tier: it runs the campaign dispatcher on a timer, holds per-account BullMQ
  # consumers, and builds a GraphQL schema at boot.
  cpu    = 512
  memory = 1024

  # ───────────────────────────────────────────────────────────────────────────
  # ONE TASK, AND IT IS A CORRECTNESS CONSTRAINT.
  #
  # 0/100 makes ECS stop the running task before starting its replacement. The
  # defaults (100/200) do the opposite, which is right for a stateless service
  # and would be a defect here: two API instances means two campaign dispatchers
  # independently deciding the same enrolment is ready to send, and the failure
  # is a duplicate LinkedIn invitation to a real person that cannot be
  # withdrawn. k8s/api-deployment.yaml says `strategy: Recreate` for this exact
  # reason and says so at length.
  #
  # The cost is a few seconds of downtime per deploy. That is the trade the
  # product already made.
  # ───────────────────────────────────────────────────────────────────────────
  deployment_minimum_healthy_percent = 0
  deployment_maximum_percent         = 100

  # Zero until the first real image exists; the pipeline raises it.
  desired_count = 0

  environment = {
    NODE_ENV = "production"
    PORT     = "3001"
  }

  secret_arns     = var.linkedout_secret_arns
  certificate_arn = var.linkedout_certificate_arn
}

# /health and /health/ready answer for the load balancer and for nothing else.
#
# k8s/ingress.yaml enumerates /graphql and /api explicitly and leaves the health
# endpoints out, with the reason written down: a readiness endpoint that names
# which datastore is down is useful to an operator inside the cluster and free
# reconnaissance to anybody else. The ALB's default action forwards everything,
# so without this rule the ECS deployment would publish what the Kubernetes one
# deliberately does not.
#
# Priority 1: ahead of every host rule, so it holds however many services later
# share this balancer. Target-group health checks are unaffected -- they come
# from the balancer to the task directly and never traverse a listener rule.
resource "aws_lb_listener_rule" "linkedout_hide_health" {
  listener_arn = module.linkedout.https_listener_arn
  priority     = 1

  condition {
    path_pattern {
      values = ["/health", "/health/*"]
    }
  }

  action {
    type = "fixed-response"
    fixed_response {
      content_type = "text/plain"
      message_body = "Not found"
      status_code  = "404"
    }
  }
}

output "linkedout" {
  value = {
    alb            = module.linkedout.alb_dns_name
    ecr            = module.linkedout.ecr_repository_url
    service        = module.linkedout.service_name
    task_role      = module.linkedout.task_role_arn
    execution_role = module.linkedout.task_execution_role_arn
    url            = "https://api.linkedout.wezerostudio.com"
    database       = aws_db_instance.linkedout.address
    redis          = aws_elasticache_replication_group.linkedout.primary_endpoint_address
    # Where the generated master password lives. The application does not use
    # this login -- it connects as app_user, which the migrations create.
    master_secret = aws_db_instance.linkedout.master_user_secret[0].secret_arn
  }
}

# ---- the portal -------------------------------------------------------------
# Next.js with output: 'standalone', so a Node service rather than a static
# bundle. Attached to the API's load balancer: a host rule sends
# linkedout.wezerostudio.com here and api.linkedout.wezerostudio.com keeps
# reaching the API.
module "linkedout_portal" {
  source = "../../modules/fargate-attached"

  app          = "linkedout-portal"
  cluster_name = var.ecs_cluster_name
  vpc_id       = data.aws_vpc.default.id
  subnet_ids   = slice(sort(data.aws_subnets.default.ids), 0, 2)

  listener_arn          = module.linkedout.https_listener_arn
  alb_security_group_id = module.linkedout.alb_security_group_id
  certificate_arn       = var.linkedout_portal_certificate_arn
  host_header           = "linkedout.wezerostudio.com"
  rule_priority         = 100

  container_port = 3000
  # Every path is behind the AuthKit proxy, which answers an unauthenticated
  # request with a 307 to WorkOS -- not a 200. /sign-in is exempt by name in
  # apps/portal/src/middleware.ts, so it is the one path that returns a page to
  # a health check, and therefore the one worth checking.
  health_path = "/sign-in"

  cpu           = 512
  memory        = 1024
  desired_count = 0

  # Both NEXT_PUBLIC_* values are here rather than baked into the image, and that
  # was checked rather than assumed. The repository said the opposite in two
  # places -- "must arrive as a --build-arg", "one image per environment" -- and
  # on Next 16 with Turbopack it is no longer true: the built edge bundle keeps
  # `process.env.NEXT_PUBLIC_WORKOS_REDIRECT_URI` verbatim, and a standalone
  # server started with the value only in its environment redirects to it. Method
  # and evidence are in apps/portal/Dockerfile.
  #
  # It still would be true of a value read from a "use client" component, which
  # is compiled into the browser bundle. Nothing in this portal does that today.
  environment = {
    NODE_ENV                        = "production"
    NEXT_PUBLIC_API_URL             = "https://api.linkedout.wezerostudio.com"
    NEXT_PUBLIC_WORKOS_REDIRECT_URI = "https://linkedout.wezerostudio.com/callback"
  }

  # WORKOS_API_KEY, WORKOS_CLIENT_ID and WORKOS_COOKIE_PASSWORD. authkit-nextjs
  # reads these through a dynamic process.env[name] lookup, so they are runtime
  # values too -- they are secrets rather than environment because they are
  # credentials, not because of how they are read.
  secret_arns = var.linkedout_portal_secret_arns
}

output "linkedout_portal" {
  value = {
    ecr     = module.linkedout_portal.ecr_repository_url
    service = module.linkedout_portal.service_name
    url     = "https://linkedout.wezerostudio.com"
  }
}
